AllCops:
  Exclude:
    - metadata.rb
    - ./bundle

LineLength:
  Enabled: false
MethodLength:
  Max: 30
Documentation:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
PerceivedComplexity:
  Max: 15
Metrics/AbcSize:
  Enabled: false