AllCops:
  Exclude:
    - metadata.rb
    - ./bundle

LineLength:
  Enabled: false
MethodLength:
  Max: 30
Metrics/BlockLength:
  Exclude:
  - 'spec/netapp_e_series_api_spec.rb'
  - 'spec/helper_spec.rb'
Documentation:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
PerceivedComplexity:
  Max: 15
AbcSize:
  Enabled: false
NumericLiterals:
  Enabled: false