name             'netapp_e'
maintainer       'Chef Software, Inc.'
maintainer_email 'partnereng@chef.io'
license          'Apache 2.0'
description      'Manages NetApp E-Series storage systems'
long_description 'Installs the NetApp SANtricity Web Services Proxy and manages E-Series storage systems'
version          '1.1.0'

supports 'redhat'
supports 'windows'
